modLoader="javafml"
loaderVersion="[34,)"
license="MIT"
# issueTrackerURL="https://github.com/PlatinPython/RGBBlocks/issues"

[[mods]]
  modId="particlegenerator"
  version="${file.jarVersion}"
  displayName="Particle Generator"
  authors="PlatinPython"
  description="Adds a block that can generate custom particles."
  # logoFile="logo.png"
  # logoBlur=true
  # credits="Thanks TobiBenzi for the logo and some textures"
  # displayURL="https://www.curseforge.com/minecraft/mc-mods/rgb-blocks-forge"

[[dependencies.particlegenerator]]
  modId="forge"
  mandatory=true
  versionRange="[34,)"
  ordering="NONE"
  side="BOTH"

[[dependencies.particlegenerator]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.16.3,)"
  ordering="NONE"
  side="BOTH"
