modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"
issueTrackerURL = "https://github.com/PlatinPython/VFXGenerator/issues"

[[mods]]
modId = "vfxgenerator"
version = "${file.jarVersion}"
displayName = "VFX Generator"
authors = "PlatinPython"
description = "Adds a block that can generate custom visual effects."
logoFile = "logo.png"
credits = "Thanks TobiBenzi for modeling and texturing."
displayURL = "https://www.curseforge.com/minecraft/mc-mods/vfx-generator"

[[accessTransformers]]
file = "META-INF/accesstransformers.cfg"

[[dependencies.vfxgenerator]]
modId = "neoforge"
versionRange = "[21.0,)"

[[dependencies.vfxgenerator]]
modId = "minecraft"
versionRange = "[1.21,)"
