name: Feature request
description: Suggest an idea/feature
title: "[Feature]: "
assignees: PlatinPython
labels:
  - enhancement
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the feature you want.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Description
      description: A short description of the feature you want.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Ideas on how to implement it
      description: If you have ideas on how to implement the feature you want.