name: Question
description: If you have a problem that does not fit the other templates
title: "[Question]: "
assignees: PlatinPython
labels:
  - question
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the question you have.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Question
    validations:
      required: true